import os
import tempfile

from mcpdocs.models import ServerSpec
from mcpdocs.renderer import Renderer


class TestRenderer:
    def test_render_creates_all_files(self, full_server_spec: ServerSpec) -> None:
        renderer = Renderer()
        with tempfile.TemporaryDirectory() as tmpdir:
            renderer.render(full_server_spec, tmpdir)

            assert os.path.isfile(os.path.join(tmpdir, "index.html"))
            assert os.path.isfile(os.path.join(tmpdir, "resources.html"))
            assert os.path.isfile(os.path.join(tmpdir, "prompts.html"))
            assert os.path.isfile(os.path.join(tmpdir, "static", "style.css"))

    def test_index_contains_server_name(self, full_server_spec: ServerSpec) -> None:
        renderer = Renderer()
        with tempfile.TemporaryDirectory() as tmpdir:
            renderer.render(full_server_spec, tmpdir)
            content = open(os.path.join(tmpdir, "index.html")).read()

            assert "test-server" in content
            assert "2.0.0" in content

    def test_tools_page_lists_all_tools(self, full_server_spec: ServerSpec) -> None:
        renderer = Renderer()
        with tempfile.TemporaryDirectory() as tmpdir:
            renderer.render(full_server_spec, tmpdir)
            content = open(os.path.join(tmpdir, "index.html")).read()

            assert "list_items" in content
            assert "delete_item" in content

    def test_tools_page_shows_parameters(self, full_server_spec: ServerSpec) -> None:
        renderer = Renderer()
        with tempfile.TemporaryDirectory() as tmpdir:
            renderer.render(full_server_spec, tmpdir)
            content = open(os.path.join(tmpdir, "index.html")).read()

            assert "limit" in content
            assert "offset" in content
            assert "Max items to return" in content

    def test_tools_page_shows_annotation_badges(
        self, full_server_spec: ServerSpec
    ) -> None:
        renderer = Renderer()
        with tempfile.TemporaryDirectory() as tmpdir:
            renderer.render(full_server_spec, tmpdir)
            content = open(os.path.join(tmpdir, "index.html")).read()

            assert "read-only" in content
            assert "destructive" in content

    def test_resources_page_lists_resources(self, full_server_spec: ServerSpec) -> None:
        renderer = Renderer()
        with tempfile.TemporaryDirectory() as tmpdir:
            renderer.render(full_server_spec, tmpdir)
            content = open(os.path.join(tmpdir, "resources.html")).read()

            assert "settings" in content
            assert "config://settings" in content

    def test_resources_page_lists_templates(self, full_server_spec: ServerSpec) -> None:
        renderer = Renderer()
        with tempfile.TemporaryDirectory() as tmpdir:
            renderer.render(full_server_spec, tmpdir)
            content = open(os.path.join(tmpdir, "resources.html")).read()

            assert "data_item" in content
            assert "data://{collection}/{id}" in content

    def test_prompts_page_lists_prompts(self, full_server_spec: ServerSpec) -> None:
        renderer = Renderer()
        with tempfile.TemporaryDirectory() as tmpdir:
            renderer.render(full_server_spec, tmpdir)
            content = open(os.path.join(tmpdir, "prompts.html")).read()

            assert "debug_error" in content
            assert "error" in content
            assert "context" in content

    def test_minimal_spec_hides_empty_nav_links(
        self, minimal_server_spec: ServerSpec
    ) -> None:
        renderer = Renderer()
        with tempfile.TemporaryDirectory() as tmpdir:
            renderer.render(minimal_server_spec, tmpdir)

            content = open(os.path.join(tmpdir, "index.html")).read()
            assert "minimal-server" in content
            # Nav should not show Resources or Prompts links (counts are 0)
            assert "Resources (0)" not in content
            assert "Prompts (0)" not in content

    def test_footer_contains_mcpdocs_version(
        self, full_server_spec: ServerSpec
    ) -> None:
        renderer = Renderer()
        with tempfile.TemporaryDirectory() as tmpdir:
            renderer.render(full_server_spec, tmpdir)
            content = open(os.path.join(tmpdir, "index.html")).read()

            assert "mcpdocs" in content
            assert "Generated by" in content
